name: ect
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.10
  # Required
  - cartopy
  - cftime
  - dask
  - geopandas >= 0.14
  - matplotlib-base
  - numcodecs
  - numpy
  - numba > 0.35
  - pandas
  - pyproj
  - python-dateutil
  - shapely
  - simplekml
  - six
  - xarray
  - xcube >= 1.8.0
  - xcube-cci >= 0.11.1
  - zarr <3  # until we can ensure zarr 3 compatibility
  # Test libs
  - pytest
  - pytest-cov
